# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import blueprints_pb2 as blueprints__pb2


class ArtifactServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/model.ArtifactService/Ping',
        request_serializer=blueprints__pb2.PingRequest.SerializeToString,
        response_deserializer=blueprints__pb2.PingResponse.FromString,
        )
    self.Talk = channel.unary_unary(
        '/model.ArtifactService/Talk',
        request_serializer=blueprints__pb2.BotMessage.SerializeToString,
        response_deserializer=blueprints__pb2.BotResponse.FromString,
        )
    self.SetSlot = channel.unary_unary(
        '/model.ArtifactService/SetSlot',
        request_serializer=blueprints__pb2.BotSetSlot.SerializeToString,
        response_deserializer=blueprints__pb2.BotAck.FromString,
        )


class ArtifactServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Talk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetSlot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ArtifactServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=blueprints__pb2.PingRequest.FromString,
          response_serializer=blueprints__pb2.PingResponse.SerializeToString,
      ),
      'Talk': grpc.unary_unary_rpc_method_handler(
          servicer.Talk,
          request_deserializer=blueprints__pb2.BotMessage.FromString,
          response_serializer=blueprints__pb2.BotResponse.SerializeToString,
      ),
      'SetSlot': grpc.unary_unary_rpc_method_handler(
          servicer.SetSlot,
          request_deserializer=blueprints__pb2.BotSetSlot.FromString,
          response_serializer=blueprints__pb2.BotAck.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'model.ArtifactService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
