# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blueprints.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import values_pb2 as values__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='blueprints.proto',
  package='model',
  syntax='proto3',
  serialized_options=_b('\n\024com.sagas.meta.modelP\001'),
  serialized_pb=_b('\n\x10\x62lueprints.proto\x12\x05model\x1a\x0cvalues.proto\"(\n\tBlueOffer\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05offer\x18\x02 \x01(\x03\"<\n\x0b\x42lueMessage\x12\x11\n\tactorPath\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\"i\n\nBotMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0b\x61ttachments\x18\x03 \x03(\t\x12%\n\x05slots\x18\x04 \x01(\x0b\x32\x16.model.TaStringEntries\"(\n\x0c\x42otRecipient\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"6\n\x0b\x42otResponse\x12\'\n\nrecipients\x18\x01 \x03(\x0b\x32\x13.model.BotRecipient\"8\n\nBotSetSlot\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\",\n\x06\x42otAck\x12\x11\n\terrorCode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0cPingResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"7\n\x0c\x42lueInteract\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x32\xa4\x01\n\x0f\x41rtifactService\x12\x31\n\x04Ping\x12\x12.model.PingRequest\x1a\x13.model.PingResponse\"\x00\x12/\n\x04Talk\x12\x11.model.BotMessage\x1a\x12.model.BotResponse\"\x00\x12-\n\x07SetSlot\x12\x11.model.BotSetSlot\x1a\r.model.BotAck\"\x00\x42\x18\n\x14\x63om.sagas.meta.modelP\x01\x62\x06proto3')
  ,
  dependencies=[values__pb2.DESCRIPTOR,])




_BLUEOFFER = _descriptor.Descriptor(
  name='BlueOffer',
  full_name='model.BlueOffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='model.BlueOffer.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offer', full_name='model.BlueOffer.offer', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=81,
)


_BLUEMESSAGE = _descriptor.Descriptor(
  name='BlueMessage',
  full_name='model.BlueMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actorPath', full_name='model.BlueMessage.actorPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='model.BlueMessage.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='model.BlueMessage.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=143,
)


_BOTMESSAGE = _descriptor.Descriptor(
  name='BotMessage',
  full_name='model.BotMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='model.BotMessage.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='model.BotMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attachments', full_name='model.BotMessage.attachments', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slots', full_name='model.BotMessage.slots', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=250,
)


_BOTRECIPIENT = _descriptor.Descriptor(
  name='BotRecipient',
  full_name='model.BotRecipient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='model.BotRecipient.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='model.BotRecipient.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=292,
)


_BOTRESPONSE = _descriptor.Descriptor(
  name='BotResponse',
  full_name='model.BotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recipients', full_name='model.BotResponse.recipients', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=348,
)


_BOTSETSLOT = _descriptor.Descriptor(
  name='BotSetSlot',
  full_name='model.BotSetSlot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='model.BotSetSlot.event', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='model.BotSetSlot.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.BotSetSlot.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=406,
)


_BOTACK = _descriptor.Descriptor(
  name='BotAck',
  full_name='model.BotAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='model.BotAck.errorCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='model.BotAck.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=452,
)


_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='model.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='model.PingRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=484,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='model.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='model.PingResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=518,
)


_BLUEINTERACT = _descriptor.Descriptor(
  name='BlueInteract',
  full_name='model.BlueInteract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='model.BlueInteract.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='model.BlueInteract.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='model.BlueInteract.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=575,
)

_BOTMESSAGE.fields_by_name['slots'].message_type = values__pb2._TASTRINGENTRIES
_BOTRESPONSE.fields_by_name['recipients'].message_type = _BOTRECIPIENT
DESCRIPTOR.message_types_by_name['BlueOffer'] = _BLUEOFFER
DESCRIPTOR.message_types_by_name['BlueMessage'] = _BLUEMESSAGE
DESCRIPTOR.message_types_by_name['BotMessage'] = _BOTMESSAGE
DESCRIPTOR.message_types_by_name['BotRecipient'] = _BOTRECIPIENT
DESCRIPTOR.message_types_by_name['BotResponse'] = _BOTRESPONSE
DESCRIPTOR.message_types_by_name['BotSetSlot'] = _BOTSETSLOT
DESCRIPTOR.message_types_by_name['BotAck'] = _BOTACK
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['BlueInteract'] = _BLUEINTERACT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlueOffer = _reflection.GeneratedProtocolMessageType('BlueOffer', (_message.Message,), dict(
  DESCRIPTOR = _BLUEOFFER,
  __module__ = 'blueprints_pb2'
  # @@protoc_insertion_point(class_scope:model.BlueOffer)
  ))
_sym_db.RegisterMessage(BlueOffer)

BlueMessage = _reflection.GeneratedProtocolMessageType('BlueMessage', (_message.Message,), dict(
  DESCRIPTOR = _BLUEMESSAGE,
  __module__ = 'blueprints_pb2'
  # @@protoc_insertion_point(class_scope:model.BlueMessage)
  ))
_sym_db.RegisterMessage(BlueMessage)

BotMessage = _reflection.GeneratedProtocolMessageType('BotMessage', (_message.Message,), dict(
  DESCRIPTOR = _BOTMESSAGE,
  __module__ = 'blueprints_pb2'
  # @@protoc_insertion_point(class_scope:model.BotMessage)
  ))
_sym_db.RegisterMessage(BotMessage)

BotRecipient = _reflection.GeneratedProtocolMessageType('BotRecipient', (_message.Message,), dict(
  DESCRIPTOR = _BOTRECIPIENT,
  __module__ = 'blueprints_pb2'
  # @@protoc_insertion_point(class_scope:model.BotRecipient)
  ))
_sym_db.RegisterMessage(BotRecipient)

BotResponse = _reflection.GeneratedProtocolMessageType('BotResponse', (_message.Message,), dict(
  DESCRIPTOR = _BOTRESPONSE,
  __module__ = 'blueprints_pb2'
  # @@protoc_insertion_point(class_scope:model.BotResponse)
  ))
_sym_db.RegisterMessage(BotResponse)

BotSetSlot = _reflection.GeneratedProtocolMessageType('BotSetSlot', (_message.Message,), dict(
  DESCRIPTOR = _BOTSETSLOT,
  __module__ = 'blueprints_pb2'
  # @@protoc_insertion_point(class_scope:model.BotSetSlot)
  ))
_sym_db.RegisterMessage(BotSetSlot)

BotAck = _reflection.GeneratedProtocolMessageType('BotAck', (_message.Message,), dict(
  DESCRIPTOR = _BOTACK,
  __module__ = 'blueprints_pb2'
  # @@protoc_insertion_point(class_scope:model.BotAck)
  ))
_sym_db.RegisterMessage(BotAck)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQUEST,
  __module__ = 'blueprints_pb2'
  # @@protoc_insertion_point(class_scope:model.PingRequest)
  ))
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), dict(
  DESCRIPTOR = _PINGRESPONSE,
  __module__ = 'blueprints_pb2'
  # @@protoc_insertion_point(class_scope:model.PingResponse)
  ))
_sym_db.RegisterMessage(PingResponse)

BlueInteract = _reflection.GeneratedProtocolMessageType('BlueInteract', (_message.Message,), dict(
  DESCRIPTOR = _BLUEINTERACT,
  __module__ = 'blueprints_pb2'
  # @@protoc_insertion_point(class_scope:model.BlueInteract)
  ))
_sym_db.RegisterMessage(BlueInteract)


DESCRIPTOR._options = None

_ARTIFACTSERVICE = _descriptor.ServiceDescriptor(
  name='ArtifactService',
  full_name='model.ArtifactService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=578,
  serialized_end=742,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='model.ArtifactService.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Talk',
    full_name='model.ArtifactService.Talk',
    index=1,
    containing_service=None,
    input_type=_BOTMESSAGE,
    output_type=_BOTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetSlot',
    full_name='model.ArtifactService.SetSlot',
    index=2,
    containing_service=None,
    input_type=_BOTSETSLOT,
    output_type=_BOTACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARTIFACTSERVICE)

DESCRIPTOR.services_by_name['ArtifactService'] = _ARTIFACTSERVICE

# @@protoc_insertion_point(module_scope)
