# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mess.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mess.proto',
  package='model',
  syntax='proto3',
  serialized_options=_b('\n\024com.sagas.meta.modelP\001'),
  serialized_pb=_b('\n\nmess.proto\x12\x05model\"\x1a\n\nMessString\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\"P\n\x0cTextLangInfo\x12\x0c\n\x04lang\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x10\n\x08reliable\x18\x04 \x01(\x08\x32\x43\n\x0bMessService\x12\x34\n\x08SayHello\x12\x11.model.MessString\x1a\x13.model.TextLangInfo\"\x00\x42\x18\n\x14\x63om.sagas.meta.modelP\x01\x62\x06proto3')
)




_MESSSTRING = _descriptor.Descriptor(
  name='MessString',
  full_name='model.MessString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='model.MessString.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=47,
)


_TEXTLANGINFO = _descriptor.Descriptor(
  name='TextLangInfo',
  full_name='model.TextLangInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lang', full_name='model.TextLangInfo.lang', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='model.TextLangInfo.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='model.TextLangInfo.confidence', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reliable', full_name='model.TextLangInfo.reliable', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['MessString'] = _MESSSTRING
DESCRIPTOR.message_types_by_name['TextLangInfo'] = _TEXTLANGINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessString = _reflection.GeneratedProtocolMessageType('MessString', (_message.Message,), dict(
  DESCRIPTOR = _MESSSTRING,
  __module__ = 'mess_pb2'
  # @@protoc_insertion_point(class_scope:model.MessString)
  ))
_sym_db.RegisterMessage(MessString)

TextLangInfo = _reflection.GeneratedProtocolMessageType('TextLangInfo', (_message.Message,), dict(
  DESCRIPTOR = _TEXTLANGINFO,
  __module__ = 'mess_pb2'
  # @@protoc_insertion_point(class_scope:model.TextLangInfo)
  ))
_sym_db.RegisterMessage(TextLangInfo)


DESCRIPTOR._options = None

_MESSSERVICE = _descriptor.ServiceDescriptor(
  name='MessService',
  full_name='model.MessService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=131,
  serialized_end=198,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='model.MessService.SayHello',
    index=0,
    containing_service=None,
    input_type=_MESSSTRING,
    output_type=_TEXTLANGINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSSERVICE)

DESCRIPTOR.services_by_name['MessService'] = _MESSSERVICE

# @@protoc_insertion_point(module_scope)
