# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mess_pb2 as mess__pb2


class MessServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/model.MessService/SayHello',
        request_serializer=mess__pb2.MessString.SerializeToString,
        response_deserializer=mess__pb2.TextLangInfo.FromString,
        )


class MessServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=mess__pb2.MessString.FromString,
          response_serializer=mess__pb2.TextLangInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'model.MessService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
