# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: options.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='options.proto',
  package='model',
  syntax='proto3',
  serialized_options=_b('\n\024com.sagas.meta.modelP\001'),
  serialized_pb=_b('\n\roptions.proto\x12\x05model\"R\n\rTaFindOptions\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x10\n\x08\x64istinct\x18\x03 \x01(\x08\x12\x10\n\x08useCache\x18\x04 \x01(\x08\x42\x18\n\x14\x63om.sagas.meta.modelP\x01\x62\x06proto3')
)




_TAFINDOPTIONS = _descriptor.Descriptor(
  name='TaFindOptions',
  full_name='model.TaFindOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='model.TaFindOptions.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='model.TaFindOptions.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distinct', full_name='model.TaFindOptions.distinct', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='useCache', full_name='model.TaFindOptions.useCache', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['TaFindOptions'] = _TAFINDOPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaFindOptions = _reflection.GeneratedProtocolMessageType('TaFindOptions', (_message.Message,), dict(
  DESCRIPTOR = _TAFINDOPTIONS,
  __module__ = 'options_pb2'
  # @@protoc_insertion_point(class_scope:model.TaFindOptions)
  ))
_sym_db.RegisterMessage(TaFindOptions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
