# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resources.proto',
  package='model',
  syntax='proto3',
  serialized_options=_b('\n\024com.sagas.meta.modelP\001'),
  serialized_pb=_b('\n\x0fresources.proto\x12\x05model\"\x89\x01\n\nRsResource\x12\x35\n\nproperties\x18\x01 \x03(\x0b\x32!.model.RsResource.PropertiesEntry\x1a\x44\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.model.RsProperty:\x02\x38\x01\"\x89\x01\n\nRsProperty\x12\x0b\n\x03key\x18\x01 \x01(\t\x12-\n\x06values\x18\x02 \x03(\x0b\x32\x1d.model.RsProperty.ValuesEntry\x12\x10\n\x08location\x18\x03 \x01(\t\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1a\n\tRsStrings\x12\r\n\x05value\x18\x01 \x03(\t\"y\n\x07RsIndex\x12,\n\x07indexes\x18\x01 \x03(\x0b\x32\x1b.model.RsIndex.IndexesEntry\x1a@\n\x0cIndexesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.model.RsStrings:\x02\x38\x01\"\x84\x01\n\tRsLookups\x12\x34\n\nindexTable\x18\x01 \x03(\x0b\x32 .model.RsLookups.IndexTableEntry\x1a\x41\n\x0fIndexTableEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.model.RsIndex:\x02\x38\x01\"4\n\x11RsEntityReference\x12\x10\n\x08\x65ntities\x18\x01 \x03(\t\x12\r\n\x05views\x18\x02 \x03(\t\"\x8d\x01\n\nRsEntities\x12\x33\n\tfieldRefs\x18\x01 \x03(\x0b\x32 .model.RsEntities.FieldRefsEntry\x1aJ\n\x0e\x46ieldRefsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.model.RsEntityReference:\x02\x38\x01\"K\n\x06RsLang\x12\x0f\n\x07\x65ntries\x18\x01 \x03(\t\x12\r\n\x05store\x18\x02 \x01(\x0c\x12\r\n\x05verbs\x18\x03 \x03(\t\x12\x12\n\nverbLemmas\x18\x04 \x03(\t\"\'\n\x07RsLangs\x12\x1c\n\x05langs\x18\x01 \x03(\x0b\x32\r.model.RsLangB\x18\n\x14\x63om.sagas.meta.modelP\x01\x62\x06proto3')
)




_RSRESOURCE_PROPERTIESENTRY = _descriptor.Descriptor(
  name='PropertiesEntry',
  full_name='model.RsResource.PropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.RsResource.PropertiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.RsResource.PropertiesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=164,
)

_RSRESOURCE = _descriptor.Descriptor(
  name='RsResource',
  full_name='model.RsResource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='properties', full_name='model.RsResource.properties', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RSRESOURCE_PROPERTIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=164,
)


_RSPROPERTY_VALUESENTRY = _descriptor.Descriptor(
  name='ValuesEntry',
  full_name='model.RsProperty.ValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.RsProperty.ValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.RsProperty.ValuesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=304,
)

_RSPROPERTY = _descriptor.Descriptor(
  name='RsProperty',
  full_name='model.RsProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.RsProperty.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='model.RsProperty.values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='model.RsProperty.location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RSPROPERTY_VALUESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=304,
)


_RSSTRINGS = _descriptor.Descriptor(
  name='RsStrings',
  full_name='model.RsStrings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='model.RsStrings.value', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=332,
)


_RSINDEX_INDEXESENTRY = _descriptor.Descriptor(
  name='IndexesEntry',
  full_name='model.RsIndex.IndexesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.RsIndex.IndexesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.RsIndex.IndexesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=455,
)

_RSINDEX = _descriptor.Descriptor(
  name='RsIndex',
  full_name='model.RsIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='indexes', full_name='model.RsIndex.indexes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RSINDEX_INDEXESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=455,
)


_RSLOOKUPS_INDEXTABLEENTRY = _descriptor.Descriptor(
  name='IndexTableEntry',
  full_name='model.RsLookups.IndexTableEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.RsLookups.IndexTableEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.RsLookups.IndexTableEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=590,
)

_RSLOOKUPS = _descriptor.Descriptor(
  name='RsLookups',
  full_name='model.RsLookups',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='indexTable', full_name='model.RsLookups.indexTable', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RSLOOKUPS_INDEXTABLEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=590,
)


_RSENTITYREFERENCE = _descriptor.Descriptor(
  name='RsEntityReference',
  full_name='model.RsEntityReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entities', full_name='model.RsEntityReference.entities', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='views', full_name='model.RsEntityReference.views', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=644,
)


_RSENTITIES_FIELDREFSENTRY = _descriptor.Descriptor(
  name='FieldRefsEntry',
  full_name='model.RsEntities.FieldRefsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.RsEntities.FieldRefsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.RsEntities.FieldRefsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=714,
  serialized_end=788,
)

_RSENTITIES = _descriptor.Descriptor(
  name='RsEntities',
  full_name='model.RsEntities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fieldRefs', full_name='model.RsEntities.fieldRefs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RSENTITIES_FIELDREFSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=647,
  serialized_end=788,
)


_RSLANG = _descriptor.Descriptor(
  name='RsLang',
  full_name='model.RsLang',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='model.RsLang.entries', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='store', full_name='model.RsLang.store', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verbs', full_name='model.RsLang.verbs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verbLemmas', full_name='model.RsLang.verbLemmas', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=790,
  serialized_end=865,
)


_RSLANGS = _descriptor.Descriptor(
  name='RsLangs',
  full_name='model.RsLangs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='langs', full_name='model.RsLangs.langs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=867,
  serialized_end=906,
)

_RSRESOURCE_PROPERTIESENTRY.fields_by_name['value'].message_type = _RSPROPERTY
_RSRESOURCE_PROPERTIESENTRY.containing_type = _RSRESOURCE
_RSRESOURCE.fields_by_name['properties'].message_type = _RSRESOURCE_PROPERTIESENTRY
_RSPROPERTY_VALUESENTRY.containing_type = _RSPROPERTY
_RSPROPERTY.fields_by_name['values'].message_type = _RSPROPERTY_VALUESENTRY
_RSINDEX_INDEXESENTRY.fields_by_name['value'].message_type = _RSSTRINGS
_RSINDEX_INDEXESENTRY.containing_type = _RSINDEX
_RSINDEX.fields_by_name['indexes'].message_type = _RSINDEX_INDEXESENTRY
_RSLOOKUPS_INDEXTABLEENTRY.fields_by_name['value'].message_type = _RSINDEX
_RSLOOKUPS_INDEXTABLEENTRY.containing_type = _RSLOOKUPS
_RSLOOKUPS.fields_by_name['indexTable'].message_type = _RSLOOKUPS_INDEXTABLEENTRY
_RSENTITIES_FIELDREFSENTRY.fields_by_name['value'].message_type = _RSENTITYREFERENCE
_RSENTITIES_FIELDREFSENTRY.containing_type = _RSENTITIES
_RSENTITIES.fields_by_name['fieldRefs'].message_type = _RSENTITIES_FIELDREFSENTRY
_RSLANGS.fields_by_name['langs'].message_type = _RSLANG
DESCRIPTOR.message_types_by_name['RsResource'] = _RSRESOURCE
DESCRIPTOR.message_types_by_name['RsProperty'] = _RSPROPERTY
DESCRIPTOR.message_types_by_name['RsStrings'] = _RSSTRINGS
DESCRIPTOR.message_types_by_name['RsIndex'] = _RSINDEX
DESCRIPTOR.message_types_by_name['RsLookups'] = _RSLOOKUPS
DESCRIPTOR.message_types_by_name['RsEntityReference'] = _RSENTITYREFERENCE
DESCRIPTOR.message_types_by_name['RsEntities'] = _RSENTITIES
DESCRIPTOR.message_types_by_name['RsLang'] = _RSLANG
DESCRIPTOR.message_types_by_name['RsLangs'] = _RSLANGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RsResource = _reflection.GeneratedProtocolMessageType('RsResource', (_message.Message,), dict(

  PropertiesEntry = _reflection.GeneratedProtocolMessageType('PropertiesEntry', (_message.Message,), dict(
    DESCRIPTOR = _RSRESOURCE_PROPERTIESENTRY,
    __module__ = 'resources_pb2'
    # @@protoc_insertion_point(class_scope:model.RsResource.PropertiesEntry)
    ))
  ,
  DESCRIPTOR = _RSRESOURCE,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:model.RsResource)
  ))
_sym_db.RegisterMessage(RsResource)
_sym_db.RegisterMessage(RsResource.PropertiesEntry)

RsProperty = _reflection.GeneratedProtocolMessageType('RsProperty', (_message.Message,), dict(

  ValuesEntry = _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), dict(
    DESCRIPTOR = _RSPROPERTY_VALUESENTRY,
    __module__ = 'resources_pb2'
    # @@protoc_insertion_point(class_scope:model.RsProperty.ValuesEntry)
    ))
  ,
  DESCRIPTOR = _RSPROPERTY,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:model.RsProperty)
  ))
_sym_db.RegisterMessage(RsProperty)
_sym_db.RegisterMessage(RsProperty.ValuesEntry)

RsStrings = _reflection.GeneratedProtocolMessageType('RsStrings', (_message.Message,), dict(
  DESCRIPTOR = _RSSTRINGS,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:model.RsStrings)
  ))
_sym_db.RegisterMessage(RsStrings)

RsIndex = _reflection.GeneratedProtocolMessageType('RsIndex', (_message.Message,), dict(

  IndexesEntry = _reflection.GeneratedProtocolMessageType('IndexesEntry', (_message.Message,), dict(
    DESCRIPTOR = _RSINDEX_INDEXESENTRY,
    __module__ = 'resources_pb2'
    # @@protoc_insertion_point(class_scope:model.RsIndex.IndexesEntry)
    ))
  ,
  DESCRIPTOR = _RSINDEX,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:model.RsIndex)
  ))
_sym_db.RegisterMessage(RsIndex)
_sym_db.RegisterMessage(RsIndex.IndexesEntry)

RsLookups = _reflection.GeneratedProtocolMessageType('RsLookups', (_message.Message,), dict(

  IndexTableEntry = _reflection.GeneratedProtocolMessageType('IndexTableEntry', (_message.Message,), dict(
    DESCRIPTOR = _RSLOOKUPS_INDEXTABLEENTRY,
    __module__ = 'resources_pb2'
    # @@protoc_insertion_point(class_scope:model.RsLookups.IndexTableEntry)
    ))
  ,
  DESCRIPTOR = _RSLOOKUPS,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:model.RsLookups)
  ))
_sym_db.RegisterMessage(RsLookups)
_sym_db.RegisterMessage(RsLookups.IndexTableEntry)

RsEntityReference = _reflection.GeneratedProtocolMessageType('RsEntityReference', (_message.Message,), dict(
  DESCRIPTOR = _RSENTITYREFERENCE,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:model.RsEntityReference)
  ))
_sym_db.RegisterMessage(RsEntityReference)

RsEntities = _reflection.GeneratedProtocolMessageType('RsEntities', (_message.Message,), dict(

  FieldRefsEntry = _reflection.GeneratedProtocolMessageType('FieldRefsEntry', (_message.Message,), dict(
    DESCRIPTOR = _RSENTITIES_FIELDREFSENTRY,
    __module__ = 'resources_pb2'
    # @@protoc_insertion_point(class_scope:model.RsEntities.FieldRefsEntry)
    ))
  ,
  DESCRIPTOR = _RSENTITIES,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:model.RsEntities)
  ))
_sym_db.RegisterMessage(RsEntities)
_sym_db.RegisterMessage(RsEntities.FieldRefsEntry)

RsLang = _reflection.GeneratedProtocolMessageType('RsLang', (_message.Message,), dict(
  DESCRIPTOR = _RSLANG,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:model.RsLang)
  ))
_sym_db.RegisterMessage(RsLang)

RsLangs = _reflection.GeneratedProtocolMessageType('RsLangs', (_message.Message,), dict(
  DESCRIPTOR = _RSLANGS,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:model.RsLangs)
  ))
_sym_db.RegisterMessage(RsLangs)


DESCRIPTOR._options = None
_RSRESOURCE_PROPERTIESENTRY._options = None
_RSPROPERTY_VALUESENTRY._options = None
_RSINDEX_INDEXESENTRY._options = None
_RSLOOKUPS_INDEXTABLEENTRY._options = None
_RSENTITIES_FIELDREFSENTRY._options = None
# @@protoc_insertion_point(module_scope)
