from sagas.nlu.mats import Cats, Mats

default = Cats('default')

Mats(cat=default) \
    .sent(ar="لقد حاولت وسعك.",
          en="I've tried your power.",
          zh="我已经尝试过你的力量了。",
          ja="あなたの力を試しました。",
          v0="Anata no chikara o tameshimashita.",
          v1="laqad hawalat wasaeik.",
          ) \
    .sent(ar="أشتاق إليه.",
          en="I miss him.",
          zh="我想念他。",
          ja="彼が恋しい",
          v0="Kare ga koishī",
          v1="'ashtaq 'iilayh.",
          ) \
    .sent(en="how are you",
          fr="Comment allez-vous",
          zh="你好吗",
          ar="كيف حالكم",
          v0="kayf halakum",
          ) \
    .sent(en="i drink tea",
          fr="je bois du thé",
          zh="我喝茶",
          ar="انا اشرب الشاي",
          v0="'iinaa ashrb alshshay",
          ) \
    .sent(en="i drink juice",
          fr="je bois du jus",
          zh="我喝果汁",
          ar="أنا أشرب العصير",
          v0="'ana 'ashrib aleasir",
          ) \
    .sent(en="i have a dog",
          fr="j'ai un chien",
          zh="我养了一条狗",
          ar="لدي كلب",
          v0="ladaya kalib",
          ) \
    .sent(en="this is my mother",
          fr="c'est ma mère",
          zh="这是我的母亲",
          ar="هذه امي",
          v0="hadhih amy",
          ) \
    .sent(en="good evening",
          fr="Bonsoir",
          zh="晚上好",
          ar="مساء الخير",
          v0="masa' alkhayr",
          ) \
    .sent(en="this is my daughter",
          fr="c'est ma fille",
          zh="这是我的女儿",
          ar="هذه ابنتي",
          v0="hadhih abnatay",
          ) \
    .sent(en="this is my brother",
          fr="C'est mon frère",
          zh="这是我的兄弟",
          ar="هذا أخي",
          v0="hadha 'akhi",
          ) \
    .sent(en="they are all here",
          fr="ils sont tous là",
          zh="他们都在这里",
          ar="انهم جميعا هنا",
          v0="'inhum jamieaan huna",
          ) \
    .sent(en="my family is here",
          fr="ma famille est là",
          zh="我的家人在这里",
          ar="عائلتي هنا",
          v0="eayilati huna",
          ) \
    .sent(en="this is my nephew",
          fr="C'est mon neveu",
          zh="这是我的侄子",
          ar="هذا ابن اختي",
          v0="hadha abn 'ukhti",
          ) \
    .sent(en="this is my aunt",
          fr="Ceci est ma tante",
          zh="这是我的阿姨",
          ar="هذه خالتي",
          v0="hadhih khalati",
          ) \
    .sent(en="this is my niece",
          fr="c'est ma nièce",
          zh="这是我的侄女",
          ar="هذه ابنة اختي",
          v0="hadhih aibnat 'ukhti",
          ) \
    .sent(en="so your whole family is here",
          fr="alors toute votre famille est ici",
          zh="所以你的全家都在这里",
          ar="لذلك عائلتك كلها هنا",
          v0="ldhlk eayiltuk klha huna",
          ) \
    .sent(en="this is my wife",
          fr="c'est ma femme",
          zh="这是我的妻子",
          ar="هذه زوجتي",
          v0="hadhih zawjati",
          ) \
    .sent(en="this is my best friend",
          fr="C'est mon meilleur ami",
          zh="这是我最好的朋友",
          ar="هذا صديقي المفضل",
          v0="hadha sadiqi almufadal",
          ) \
    .sent(en="what is your name",
          fr="quel est votre nom",
          zh="你叫什么名字",
          ar="ما اسمك",
          v0="ma aismak",
          ) \
    .sent(en="we are a family",
          fr="nous sommes une famille",
          zh="我们是一家人",
          ar="نحن عائلة",
          v0="nahn eayila",
          ) \
    .sent(en="the family is not small",
          fr="la famille n'est pas petite",
          zh="这个家庭不小",
          ar="العائلة ليست صغيرة",
          v0="aleayilat laysat saghiratan",
          ) \
    .sent(en="he learns",
          fr="il apprend",
          zh="他学习",
          ar="هو يتعلم",
          v0="hu yataealam",
          ) \
    .sent(en="we are learning",
          fr="nous apprenons",
          zh="我们正在学习",
          ar="نحن نتعلم",
          v0="nahn nataealam",
          ) \
    .sent(en="i understand french",
          fr="je comprends le français",
          zh="我懂法语",
          ar="أنا أفهم الفرنسية",
          v0="'ana 'afahum alfaransia",
          ) \
    .sent(en="do you understand french",
          fr="comprenez-vous le français",
          zh="你懂法语吗",
          ar="هل تفهم الفرنسية",
          v0="hal tafahum alfaransia",
          t0="hl tfhm alfrnsyt",
          ) \
    .sent(en="france is in europe",
          fr="la france est en europe",
          zh="法国在欧洲",
          ar="فرنسا في أوروبا",
          v0="faransa fi 'uwrubba",
          t0="frnsa fy awrwba",
          ) \
    .sent(en="i write",
          fr="j'écris",
          zh="我写",
          ar="انا اكتب",
          v0="'iinaa aktub",
          t0="ana aktb",
          ) \
    .sent(en="i write a book",
          fr="J'écris un livre",
          zh="我写了一本书",
          ar="أنا أكتب كتابا",
          v0="'ana 'aktab kitabanaan",
          t0="ana aktb ktaba",
          ) \
    .sent(en="do you like to read",
          fr="aimez-vous lire",
          zh="你喜欢读书吗？",
          ar="هل تحب القراءة",
          v0="hal tuhibu alqira'a",
          t0="hl thb alqraʾt",
          ) \
    .sent(en="he translates from french to hindi",
          fr="il traduit du français en hindi",
          zh="他从法语翻译成印度语",
          ar="انه يترجم من الفرنسية إلى الهندية",
          v0="'iinah yutarjam min alfaransiat 'iilaa alhindia",
          t0="anh ytrjm mn alfrnsyt aly alhndyt",
          ) \
    .sent(en="you learn to speak english",
          fr="tu apprends à parler anglais",
          zh="你学会说英语",
          ar="تتعلم التحدث باللغة الانجليزية",
          v0="tataealam altahaduth biallughat al'iinjlizia",
          t0="ttʿlm althdth ballght alanjlyzyt",
          ) \
    .sent(en="i understand her well",
          fr="je la comprends bien",
          zh="我很了解她",
          ar="أنا أفهمها جيدا",
          v0="'ana 'afhumuha jayidaan",
          t0="ana afhmha jyda",
          ) \
    .sent(en="you are very beautiful",
          fr="vous êtes très belle",
          zh="你非常漂亮",
          ar="أنت جميلة جدا",
          v0="'ant jamilat jiddaan",
          t0="ant jmylt jda",
          ) \
    .sent(en="do you like me",
          fr="m'aimez-vous",
          zh="你喜欢我吗",
          ar="هل أعجبك",
          v0="hal 'aejabak",
          t0="hl aʿjbk",
          ) \
    .sent(en="i love you",
          fr="je t'aime",
          zh="我爱你",
          ar="انا احبك",
          v0="'iinaa ahbk",
          t0="ana ahbk",
          ) \
    .sent(en="i am not interested",
          fr="je ne suis pas intéressé",
          zh="我没兴趣",
          ar="لست مهتما",
          v0="last muhtammaan",
          t0="lst mhtma",
          ) \
    .sent(en="are you single",
          fr="es-tu célibataire",
          zh="你单身吗",
          ar="هل أنت غير مرتبط",
          v0="hal 'ant ghyr mrtbt",
          t0="hl ant ghyr mrtbt",
          ) \
    .sent(en="she smiles at him",
          fr="elle lui sourit",
          zh="她对他微笑",
          ar="هي تبتسم له",
          v0="hi tabtasim lah",
          t0="hy tbtsm lh",
          ) \
    .sent(en="she laughs at the joke",
          fr="elle rit de la blague",
          zh="她笑着开玩笑",
          ar="هي تضحك على النكتة",
          v0="hi tadhuk ealaa alnakta",
          t0="hy tdhk ʿly alnktt",
          ) \
    .sent(en="she ignored you",
          fr="elle t'a ignoré",
          zh="她不理你",
          ar="لقد تجاهلك",
          v0="laqad tajahaluk",
          t0="lqd tjahlk",
          ) \
    .sent(en="i am falling in love with you",
          fr="je tombe amoureux de toi",
          zh="我爱上了你",
          ar="انا اقع في حبك",
          v0="'iinaa aqe fi habk",
          t0="ana aqʿ fy hbk",
          ) \
    .sent(en="may i hold your hand",
          fr="puis-je te tenir la main",
          zh="我可以握住你的手",
          ar="هل لي أن أمسك يدك؟",
          v0="hal li 'ana 'amsik yadak?",
          t0="hl ly an amsk ydk?",
          ) \
    .sent(en="we'll always have paris",
          fr="nous aurons toujours paris",
          zh="我们将永远拥有巴黎",
          ar="سيكون لدينا دائما باريس",
          v0="sayakun ladayna dayimaan baris",
          t0="sykwn ldyna dayma barys",
          ) \
    .sent(en="i need you",
          fr="j'ai besoin de vous",
          zh="我需要你",
          ar="أنا بحاجة إليك",
          v0="'ana bihajat 'iilayk",
          t0="ana bhajt alyk",
          ) \
    .sent(en="do you like to go to the opera",
          fr="aimez-vous aller à l'opéra",
          zh="你喜欢去看歌剧吗？",
          ar="هل تحب الذهاب إلى الأوبرا",
          v0="hal tuhibu aldhahab 'iilaa al'awbara",
          t0="hl thb aldhhab aly alawbra",
          ) \
    .sent(en="i like to be on time",
          fr="j'aime être à l'heure",
          zh="我喜欢准时",
          ar="أحب أن أكون في الوقت المحدد",
          v0="'ahibu 'an 'akun fi alwaqt almuhadad",
          t0="ahb an akwn fy alwqt almhdd",
          ) \
    .sent(en="would you like to go for a drink",
          fr="Voulez-vous aller boire un verre",
          zh="你想去喝酒吗",
          ar="تريد أن تذهب لاحتساء شراب",
          v0="turid 'an tadhhab liaihtisa' sharab",
          t0="tryd an tdhhb lahtsaʾ shrab",
          ) \
    .sent(en="can i see you again",
          fr="est-ce que je peux vous revoir",
          zh="我能再见到你吗？",
          ar="يمكن أن أراك مرة أخرى",
          v0="ymkn 'an 'arak maratan 'ukhraa",
          t0="ymkn an arak mrt akhry",
          ) \
    .sent(en="would you like to have dinner with me",
          fr="voudrais-tu dîner avec moi",
          zh="你想和我共进晚餐吗？",
          ar="هل ترغب في تناول العشاء معي",
          v0="hal targhab fi tanawul aleasha' maeia",
          t0="hl trghb fy tnawl alʿshaʾ mʿy",
          ) \
    .sent(en="the sky is blue",
          fr="le ciel est bleu",
          zh="天是蓝的",
          ar="السماء زرقاء",
          v0="alsama' zurqa'",
          t0="alsmaʾ zrqaʾ",
          ) \
    .sent(en="the summer is warm",
          fr="l'été est chaud",
          zh="夏天很温暖",
          ar="الصيف دافئ",
          v0="alsayf dafi",
          t0="alsyf dafy",
          ) \
    .sent(en="it snows or rains in winter",
          fr="il neige ou il pleut en hiver",
          zh="冬天下雪或下雨",
          ar="تتساقط الثلوج أو تهطل الأمطار في فصل الشتاء",
          v0="tatasaqat althuluj 'aw tahtul al'amtar fi fasl alshita'",
          t0="ttsaqt althlwj aw thtl alamtar fy fsl alshtaʾ",
          ) \
    .sent(en="it is windy",
          fr="il y a du vent",
          zh="风很大",
          ar="إنه عاصف",
          v0="'iinah easif",
          t0="anh ʿasf",
          ) \
    .sent(en="it is warm today",
          fr="il fait chaud aujourd'hui",
          zh="今天好暖和",
          ar="الجو دافئ اليوم",
          v0="aljawi dafi alyawm",
          t0="aljw dafy alywm",
          ) \







