#!/bin/bash
. ~/pi/bin/inc/wait_funcs.sh
. ~/pi/bin/inc/matchers.sh
. ~/pi/bin/inc/docker_utils.sh

function start_inventory(){
	# mysqld: ready for connections.
	start_docker inventory "$msg_mysql"
}

# startup 
if [ $# -lt 1 ]; then	
	echo "available opts: all, zk, storm, repl, ..."
else
	CMD=$1
	case "$CMD" in
	"redis")
		start_docker redis "$msg_redis"
		;;
	"inventory")
		start_inventory
		;;
	"zk")
		zookeeper-server-start /usr/local/etc/kafka/zookeeper.properties
		;;
	"kf")
		kafka-server-start /usr/local/etc/kafka/server.properties
		;;
	"stop-faust")
		pkill -9 -f 'faust'
		;;
	"clean")
		rm -rf /usr/local/var/lib/kafka-logs/*
		rm -rf /usr/local/var/lib/zookeeper/*  # zookeeper
		;;
    "topics")
        kafka-topics --list --bootstrap-server localhost:9092
        ;;
	"list-ports")
		lsof -i :8080
		;;
	*)
		# default proc
		handle_cmd ${@:1}
		;;
	esac
fi

